name: Rodrigo Delduca
bio: programmer and game developer

external-image: false
picture: assets/images/profile.jpeg

dark-theme: false

resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume

url: https://nullonerror.org/

permalink: /:title/

twitter: skhaz
linkedin: skhaz
github: skhaz
email: rodrigodelduca@gmail.com

width: normal

pagination:
  enabled: false
  sort_reverse: true
  title: ":title"
  per_page: 5
  permalink: "/:num/"

projects: false

about: false
blog: false

read-time: false

show-tags: false

related: false

post-advance-links: [blog]

show-author: false

animation: false

defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "vendor",
  ]
