name: Rodrigo Delduca
bio: Lead Software Engineer

external-image: false
picture: assets/images/avatar.png

dark-theme: false

resume: true
resume-external: true
resume-url: https://gcs.skhaz.dev/resume.pdf

blog: true
blog-url: https://nullonerror.org/

url: https://rodrigo.delduca.org

permalink: /:title/

linkedin: skhaz
github: skhaz
email: rodrigodelduca@gmail.com

width: normal

pagination:
    enabled: false
    sort_reverse: true
    title: ":title"
    per_page: 5
    permalink: "/:num/"

projects: false

about: false

#blog: false

read-time: false

show-tags: false

related: false

# post-advance-links: [blog]

post-advance-links: []

show-author: false

animation: false

defaults:
    - scope:
          path: ""
          layout: "post"
      values:
          hidden: false

plugins:
    - jekyll-seo-tag
    - jekyll-gist
    - jekyll-feed

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
            - development
            - stage

exclude: ["README.md", "Gemfile", "Gemfile.lock", "vendor"]
